version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: Main

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/Main
    depends_on:
      - mongo

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo-data:
